#!/bin/bash

get_re () {
    zc "$stats_file" | grep "^RE" | tail -n +2 | cut -f 2-
}
get_ce () {
    zc "$stats_file" | grep "^CE" | tail -n +2 | cut -f 2-
}
get_ce_normal () {
    get_ce | awk '$3==0 && $4==0'
}
get_ce_unmappable () {
    get_ce | awk '$3==1'
}
get_ce_lowcomplex () {
    get_ce | awk '$4==1'
}
get_sum () {
    awk 'BEGIN{s=0} {s+=$1} END{print s}'
}

printab "cid" \
    "num.re" "bp.re" \
    "num.ce" "bp.ce" \
    "num.ce.normal" "bp.ce.normal" \
    "num.ce.unmappable" "bp.ce.unmappable" \
    "num.ce.lowcomplex" "bp.ce.lowcomplex" \
    "num.muts.normal" "bp.muts.normal" \
    "pct.bp.muts.normal"

for stats_file in graph.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].*.stats; do
#for stats_file in graph.00000000[0-9].*.stats; do
    cid=$stats_file
    cid=${cid#graph.}
    cid=${cid%%.*}

    num_re=$(get_re | wc -l)
    bp_re=$(get_re | cut -f2 | get_sum)
    num_ce=$(get_ce | wc -l)
    bp_ce=$(get_ce | cut -f2 | get_sum)
    num_ce_normal=$(get_ce_normal | wc -l)
    bp_ce_normal=$(get_ce_normal | cut -f2 | get_sum)
    num_ce_unmappable=$(get_ce_unmappable | wc -l)
    bp_ce_unmappable=$(get_ce_unmappable | cut -f2 | get_sum)
    num_ce_lowcomplex=$(get_ce_lowcomplex | wc -l)
    bp_ce_lowcomplex=$(get_ce_lowcomplex | cut -f2 | get_sum)
    num_muts_normal=$(get_ce_normal | cut -f6 | get_sum)
    bp_muts_normal=$(get_ce_normal | cut -f13 | get_sum)

    bp_ce_normal_nonzero=$bp_ce_normal
    [ "$bp_ce_normal_nonzero" -gt 0 ] || bp_ce_normal_nonzero=1

    printab "$cid" \
        "$num_re" "$bp_re" \
        "$num_ce" "$bp_ce" \
        "$num_ce_normal" "$bp_ce_normal" \
        "$num_ce_unmappable" "$bp_ce_unmappable" \
        "$num_ce_lowcomplex" "$bp_ce_lowcomplex" \
        "$num_muts_normal" "$bp_muts_normal" \
        "$(echo "scale=2; (100 * $bp_muts_normal) / $bp_ce_normal_nonzero" | bc)"
done
