#!/usr/bin/env python

import sys

targets = []
d = []

f = open(sys.argv[1])
for line in f:
    v = line.strip()
    targets.append(v)
    d.append(v)
f.close()

for line in sys.stdin:
    line = line.strip()
    a = line.split()
    if a[0] == 'ED':
        if a[1] in targets:
            if not a[2] in d:
                d.append(a[2])
        elif a[2] in targets:
            if not a[1] in d:
                d.append(a[1])

for v in d:
    print v
