#!/bin/bash
source lib.common.sh
set -eEu
set_explicit_errtrap


[ $# -eq 1 ] || crash "use: $0 <stats_file>"
get_re () {
    zc "$stats_file" | grep "^RE" | tail -n +2 | cut -f 2-
}
get_ce () {
    zc "$stats_file" | grep "^CE" | tail -n +2 | cut -f 2-
}
get_sum () {
    awk '{s+=$1} END{print s}'
}

stats_file=$1

ref_bp=63025520
printab "ref bp" "$ref_bp"

num_reads=$(get_re | wc -l)
printab "num reads" "$num_reads"
reads_bp=$(get_re | cut -f 2 | get_sum)
printab "reads bp" "$reads_bp"

printab "num contigs" "$(get_ce | wc -l)"
num_mutations=$(get_ce | cut -f 5 | get_sum)
printab "num mutations" "$num_mutations"

num_chunks=$(get_re | cut -f 3 | get_sum)
printab "num chunks" "$num_chunks"

num_chunks_mappable=$(get_re | cut -f 4 | tr ',' '\n' | grep -v '^*' | wc -l)
printab "num mappable chunks" "$num_chunks_mappable"

reads_bp_mappable=$(get_re | cut -f 4 | tr ',' '\n' | grep -v '^*' | get_sum)
printab "bp mappable" "$reads_bp_mappable" \
    "($(echo "scale=4; $reads_bp_mappable / $reads_bp" | bc))"

reads_bp_unmappable=$(get_re | cut -f 4 | tr ',' '\n' | grep '^*' | cut -c 2- | get_sum)
printab "bp unmappable" "$reads_bp_unmappable" \
    "($(echo "scale=4; $reads_bp_unmappable / $reads_bp" | bc))"

printab "bp contigs" "$(get_ce | cut -f 2 | get_sum)"
printab "bp contigs >1 chunk" "$(get_ce | awk '$3>1' | cut -f 2 | get_sum)"
printab "bp in mut" "$(get_ce | cut -f 11 | get_sum)"

printab "bp per chunk" "$(echo "scale=2; $reads_bp / $num_chunks" | bc)"
printab "mappable bp per mappable chunk" \
    "$(echo "scale=2; $reads_bp_mappable / $num_chunks_mappable" | bc)"

printab "expected bp per chunk" "$(echo "scale=2; $ref_bp / (2 * $num_reads)" | bc)"
printab "mutations per mappable chunk" "$(echo "scale=2; $num_mutations / $num_chunks_mappable" | bc)"
