#!/bin/bash
source lib.common.sh
find_my_name_and_dir "${BASH_SOURCE[0]}"
cmd="make -rR -f $MY_DIR/$MY_NAME.make $@"
echo "===== $(date +"%F %T") ===== $cmd" >> make.log
eval "$cmd" 2>&1 | tee -a make.log
