#!/usr/bin/env python

import sys


def add_header():
    print 'strict digraph graphName {'
    print 'concentrate=true'
    print 'rankdir="LR"'

def add_footer():
    print '}'

def add_node(u, l, is_unmap):
    print ('%s [label="%s"%s]' % (u, l, ['', ', style=dashed'][is_unmap]))

def add_edge(u, v, out_u, same_orient, l):
    print ('%s -> %s [dir="both",arrowtail="%s",arrowhead="%s",label="%s"%s]' %
           (u,
            v,
            ['normal', 'inv'][out_u],
            ['normal', 'inv'][(out_u + same_orient) % 2],
            l,
            ['', ', style=dashed'][nodes[u] == 1 or nodes[v] == 1]
        ))


add_header()

seen_header = False
nodes = {}

for line in sys.stdin:
    a = line.strip().split()
    # skip read entries (RE)
    if a[0] != 'CE':
        continue
    # skipheader line
    if not seen_header:
        seen_header = True
        continue
    add_node(a[1], a[1] + ':' + a[2], int(a[3]))
    nodes[a[1]] = int(a[3])
    if a[15] != '.':
        for e in a[15][1:-1].split('),('):
            b = e.split(',')
            if b[0] in nodes:
                add_edge(a[1], b[0], 0, int(b[1]), ','.join(b[2:]))
    if a[18] != '.':
        for e in a[18][1:-1].split('),('):
            b = e.split(',')
            if b[0] in nodes:
                add_edge(a[1], b[0], 1, int(b[1]), ','.join(b[2:]))

add_footer()
