#!/usr/bin/env python

import sys
import os
import re
import argparse

description = """
Using stats file produced by mac, print the lengths and the make-up of the supercontigs.
"""

parser = argparse.ArgumentParser(description=description)
parser.add_argument('input', help='stats file', action='store', nargs='?')
args = parser.parse_args()

if args.input and args.input != '-':
    in_f = open(args.input)
else:
    in_f = sys.stdin

for line in in_f:
    line = line.strip().split()
    if line[0] != 'CE':
        continue
    
